[book]
authors = ["M Algah Fattah Illahi"]
language = "en"
multilingual = false
src = "src"
title = "aryuuu.com"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/aryuuu/book-of-me"

[output.html.print]
enable = false
